### ISSUE TITLE
Supertypes of the following classes cannot be resolved

### ISSUE THREAD

**Issue by ZakariaJawas** [arthur3486/bottomsheets#3]
It keeps showing the following error when i use the Action Picker Implementation

`Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class com.arthurivanets.bottomsheets.sheets.adapters.actionpicker.ActionItem, unresolved supertypes: com.arthurivanets.adapster.model.markers.Trackable     class com.arthurivanets.bottomsheets.sheets.adapters.actionpicker.BaseActionItem, unresolved supertypes: com.arthurivanets.adapster.model.BaseItem`

**Comment by arthur3486** [comment]
Hi @ZakariaJawas !

In order to be able to use the [`ActionPickerBottomSheet`](https://github.com/arthur3486/bottomsheets/blob/master/bottomsheets-sheets/src/main/java/com/arthurivanets/bottomsheets/sheets/ActionPickerBottomSheet.java) and [`CustomActionPickerBottomSheet`](https://github.com/arthur3486/bottomsheets/blob/master/bottomsheets-sheets/src/main/java/com/arthurivanets/bottomsheets/sheets/CustomActionPickerBottomSheet.java) you need to add the [`Adapster`](https://github.com/arthur3486/adapster) dependency to your project.

Cheers :)
